// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWjjqpkFfTVHWg-Y1ZdY68lHH7z1WHSwk',
    appId: '1:708746795809:web:fffcbeecab7ad1722bfc60',
    messagingSenderId: '708746795809',
    projectId: 'database-38f1b',
    authDomain: 'database-38f1b.firebaseapp.com',
    storageBucket: 'database-38f1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gJL22ZyxhxDnMNTdkhCdIuNj9Vth9Xk',
    appId: '1:708746795809:android:b4d39de4bc0ef68b2bfc60',
    messagingSenderId: '708746795809',
    projectId: 'database-38f1b',
    storageBucket: 'database-38f1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbINbr6bwGlgjanp8Rh6pq49SiL-hbBJ4',
    appId: '1:708746795809:ios:40b37680bd5c50fe2bfc60',
    messagingSenderId: '708746795809',
    projectId: 'database-38f1b',
    storageBucket: 'database-38f1b.appspot.com',
    iosClientId: '708746795809-tti36cpsne4nv5egbd3hsqnv142ducbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.database',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbINbr6bwGlgjanp8Rh6pq49SiL-hbBJ4',
    appId: '1:708746795809:ios:40b37680bd5c50fe2bfc60',
    messagingSenderId: '708746795809',
    projectId: 'database-38f1b',
    storageBucket: 'database-38f1b.appspot.com',
    iosClientId: '708746795809-tti36cpsne4nv5egbd3hsqnv142ducbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.database',
  );
}
